language: node_js
node_js:
  - 14

script:
  - yarn
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: surge
  domain: framer-demo-dni9.surge.sh
  project: ./build/
  cleanup: false
  on:
    branch: main
