language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: framer-demo-dni9.surge.sh
  project: ./build/
  on:
    branch: main